### PR TITLE
Fix usage of deprecated api when creating HerokuAppContainer

### PR DESCRIPTION
**Pull request by breskeby**
- also updated wrapper to 5.1
- updated scans plugin to 2.1
- add logic to keep compatibility with earlier gradle versions

### CODE REVIEW

**Comment by felipefzdz** [comment]
Thanks for the PR, @breskeby!

When running `./gradlew build` on it, I get this error though:

```
    Caused by: groovy.lang.MissingPropertyException: No such property: callbackDecorator for class: com.felipefzdz.gradle.heroku.HerokuBasePlugin
        at com.felipefzdz.gradle.heroku.HerokuBasePlugin.createHerokuAppContainer(HerokuBasePlugin.groovy:93)
        at com.felipefzdz.gradle.heroku.HerokuBasePlugin$_apply_closure1.doCall(HerokuBasePlugin.groovy:33)
        at org.gradle.api.internal.FactoryNamedDomainObjectContainer$ClosureObjectFactory.create(FactoryNamedDomainObjectContainer.java:144)
```

**Comment by breskeby** [comment]
forgot a change to commit 🤦‍♂️ now it should work

**Comment by felipefzdz** [comment]
Now it says 

```
Caused by: java.lang.UnsupportedOperationException

        at com.felipefzdz.gradle.heroku.HerokuBasePlugin.getCollectionCallbackActionDecorator(HerokuBasePlugin.groovy:49)

        at com.felipefzdz.gradle.heroku.HerokuBasePlugin.createHerokuAppContainer(HerokuBasePlugin.groovy:93)

        at com.felipefzdz.gradle.heroku.HerokuBasePlugin$_apply_closure1.doCall(HerokuBasePlugin.groovy:34)
```

Not sure how the injection should work here.

**Comment by breskeby** [comment]
weired. Now I see that too. it should work. anyhow i reworked the way we resolve the DomainCollectionCallbackDecorator now in the plugin

**Comment by felipefzdz** [comment]
Looking good, thanks!

**Pull request merged**
